services:
  - type: web
    name: ᴛᴜsʜᴀʀ ᴅʀᴍ ᴛxᴛ ᴜᴘʟᴏᴀᴅᴇʀ 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: 
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      #- key: WEBHOOK
        #sync: true
      - key: PORT
        value: 8000  # Default port value, update if needed
